// @ts-check
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";
import { readFileSync } from "node:fs";

// Hashes for Starlight `is:inline` scripts and framework style attributes,
// generated by scripts/refresh-csp-hashes.mjs (run via npm run build). The
// file may be absent before the first build; that build then cannot allow
// inline scripts, and the second pass injects the computed hashes.
const cspHashes = (() => {
  try {
    return JSON.parse(readFileSync(new URL("./src/csp-hashes.json", import.meta.url), "utf8"));
  } catch {
    return { scriptHashes: [], styleAttrHashes: [] };
  }
})();

// Static site. Marketing pages live in src/pages; documentation mounts under
// /docs via explicit `slug: docs/...` frontmatter (Starlight's content folder
// name does not mount routes by itself, and Astro's `base` would relocate the
// marketing site too).
export default defineConfig({
  site: "https://babel-harness.vercel.app",
  output: "static",
  integrations: [
    starlight({
      title: "Babel Docs",
      description:
        "Task-oriented documentation for Babel Harness: install, first use, modes, and troubleshooting.",
      logo: {
        src: "./src/assets/babel-mark.svg",
        alt: "Babel",
      },
      social: [
        {
          icon: "github",
          label: "Babel on GitHub",
          href: "https://github.com/gthgomez/Babel",
        },
      ],
      // Completed pages only; placeholder sidebar entries are forbidden.
      sidebar: [
        {
          label: "Start here",
          items: ["docs"],
        },
      ],
      customCss: ["./src/styles/docs.css"],
    }),
  ],
  markdown: {
    shikiConfig: {
      // Inline style attributes would be blocked by the site CSP; emit the
      // theme as a build-generated stylesheet instead.
      inlineStyles: false,
    },
  },
  build: {
    inlineStylesheets: "auto",
  },
  security: {
    // Injects a per-page <meta http-equiv="Content-Security-Policy"> with
    // build-computed hashes for the framework's inline scripts. This is the
    // supported approach for static output; see docs/security-decision.md.
    csp: {
      directives: [
        "default-src 'self'",
        "img-src 'self' data:",
        "connect-src 'self'",
        "base-uri 'self'",
        "form-action 'none'",
      ],
      // 'wasm-unsafe-eval' is required by Pagefind's search index runtime.
      scriptDirective: {
        resources: ["'self'", "'wasm-unsafe-eval'"],
        hashes: cspHashes.scriptHashes,
      },
      styleDirective: {
        resources: ["'self'", { resource: "'unsafe-hashes'", kind: "attribute" }],
        hashes: cspHashes.styleAttrHashes.map((hash) => ({ hash, kind: "attribute" })),
      },
    },
  },
});
